[workspace]
members = [
    "common",
    "cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
clap = "4.5"
crc = "3.2"
serialport = "4.7.0"
socketcan = "3.5.0"
