[workspace]
members = [
    "common",
    "cli",
    "tui",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"

[workspace.dependencies]
clap = "4.5"
crc = "3.2"
serialport = "4.7.0"
socketcan = "3.5.0"
ratatui = "0.29"
crossterm = "0.28"
indicatif = "0.17"
